import { addDays, setHours, setMinutes } from "date-fns";
import type { GatherEvent } from "./types";

function at(dayOffset: number, hour: number, minute = 0) {
  const base = addDays(new Date(), dayOffset);
  return setMinutes(setHours(base, hour), minute).toISOString();
}

const FRIENDS = {
  alex: { name: "Alex", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=AlexEng" },
  priya: { name: "Priya", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=PriyaML" },
  sam: { name: "Sam", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=SamFounder" },
  kai: { name: "Kai", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=KaiDev" },
  jordan: { name: "Jordan", avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=JordanPM" },
};

export const MOCK_EVENTS: GatherEvent[] = [
  {
    id: "evt-1",
    title: "Ship It Weekend — 48hr AI Hackathon",
    description:
      "Build and demo an AI product in 48 hours. Mentors from top startups, free meals, GPU credits, and $25k in prizes. Teams of 1–4, all skill levels welcome.",
    category: "professional",
    startAt: at(1, 9, 0),
    endAt: at(3, 18, 0),
    venue: "Pier 27",
    address: "27 Pier 27, The Embarcadero",
    city: "San Francisco",
    lat: 37.8044,
    lng: -122.4025,
    imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
    price: 0,
    capacity: 400,
    attendeeCount: 387,
    hostName: "BuildSF",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=BSF",
    tags: ["hackathon", "AI", "startups"],
    vibe: "crowds",
    soloFriendly: true,
    friendsGoing: [FRIENDS.priya, FRIENDS.kai, FRIENDS.sam],
    featured: true,
  },
  {
    id: "evt-2",
    title: "AI & the Future of Work Panel",
    description:
      "Engineering leaders from OpenAI, Anthropic, and YC-backed startups on shipping AI in production. Q&A and recruiter office hours after.",
    category: "professional",
    startAt: at(2, 17, 0),
    endAt: at(2, 20, 0),
    venue: "Spring Studios",
    address: "50 Varick St",
    city: "New York",
    lat: 40.7234,
    lng: -74.006,
    imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80",
    price: 0,
    capacity: 150,
    attendeeCount: 112,
    hostName: "Future Work Forum",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=FWF",
    tags: ["AI", "panel", "engineering"],
    vibe: "balanced",
    soloFriendly: true,
    friendsGoing: [FRIENDS.sam, FRIENDS.alex],
    featured: true,
  },
  {
    id: "evt-3",
    title: "Founders & Coffee: Pre-Seed Edition",
    description:
      "Casual morning for technical co-founders. No pitch decks — swap stack choices, hiring war stories, and what's actually working in AI infra.",
    category: "social",
    startAt: at(3, 8, 30),
    endAt: at(3, 10, 0),
    venue: "Blue Bottle — Mint Plaza",
    address: "66 Mint St",
    city: "San Francisco",
    lat: 37.7825,
    lng: -122.4074,
    imageUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80",
    price: 0,
    capacity: 30,
    attendeeCount: 22,
    hostName: "Startup SF",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=SSF",
    tags: ["founders", "networking", "coffee"],
    vibe: "intimate",
    soloFriendly: true,
    friendsGoing: [FRIENDS.sam, FRIENDS.jordan],
  },
  {
    id: "evt-4",
    title: "LLM Hack Night — Bring Your Laptop",
    description:
      "Hands-on evening building with Claude, GPT, and open-weight models. Prompt engineering tips, RAG patterns, and live debugging with senior ML engineers.",
    category: "learning",
    startAt: at(2, 18, 30),
    endAt: at(2, 22, 0),
    venue: "GitHub HQ",
    address: "88 Colin P Kelly Jr St",
    city: "San Francisco",
    lat: 37.782,
    lng: -122.3905,
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80",
    price: 0,
    capacity: 80,
    attendeeCount: 74,
    hostName: "MLOps SF",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=MLOps",
    tags: ["LLM", "hack-night", "engineering"],
    vibe: "balanced",
    soloFriendly: true,
    friendsGoing: [FRIENDS.priya, FRIENDS.alex],
  },
  {
    id: "evt-5",
    title: "Next.js 16 Workshop — App Router Deep Dive",
    description:
      "Ship faster with Server Components, caching, and deployment on Vercel. Live coding session — clone the starter repo before you arrive.",
    category: "learning",
    startAt: at(4, 14, 0),
    endAt: at(4, 17, 0),
    venue: "SoMa Tech Hub",
    address: "665 3rd St",
    city: "San Francisco",
    lat: 37.781,
    lng: -122.396,
    imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80",
    price: 0,
    capacity: 60,
    attendeeCount: 58,
    hostName: "Frontend SF",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=FSF",
    tags: ["nextjs", "react", "workshop"],
    vibe: "balanced",
    soloFriendly: true,
    friendsGoing: [FRIENDS.kai],
  },
  {
    id: "evt-6",
    title: "Demo Day Watch Party — YC W26",
    description:
      "Stream the batch presentations with 200 builders. Pizza, predictions pool, and breakout rooms to meet people hunting co-founders.",
    category: "social",
    startAt: at(5, 17, 0),
    endAt: at(5, 21, 0),
    venue: "The Hacker Dojo",
    address: "855 Maude Ave",
    city: "Mountain View",
    lat: 37.396,
    lng: -122.049,
    imageUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&q=80",
    price: 0,
    capacity: 200,
    attendeeCount: 178,
    hostName: "YC Alumni Network",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=YCAN",
    tags: ["demo-day", "startups", "watch-party"],
    vibe: "crowds",
    soloFriendly: true,
    friendsGoing: [FRIENDS.sam, FRIENDS.jordan, FRIENDS.priya],
  },
  {
    id: "evt-7",
    title: "Open Source Contributors Social",
    description:
      "Meet maintainers from popular OSS projects. Find good-first issues, talk governance, and pair on PRs over drinks. Stickers and swag for merged commits.",
    category: "social",
    startAt: at(3, 18, 30),
    endAt: at(3, 22, 0),
    venue: "Noisebridge",
    address: "2169 Mission St",
    city: "San Francisco",
    lat: 37.762,
    lng: -122.4194,
    imageUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    price: 0,
    capacity: 120,
    attendeeCount: 95,
    hostName: "OSS Bay Area",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=OSSBA",
    tags: ["open-source", "github", "community"],
    vibe: "balanced",
    soloFriendly: true,
    friendsGoing: [FRIENDS.kai, FRIENDS.alex],
  },
  {
    id: "evt-8",
    title: "Systems Design Interview Prep — Live Mock",
    description:
      "Senior engineers run whiteboard mocks for FAANG and startup loops. Bring a problem you’re stuck on — groups rotate every 45 minutes.",
    category: "learning",
    startAt: at(6, 10, 0),
    endAt: at(6, 13, 0),
    venue: "WeWork — FiDi",
    address: "535 Mission St",
    city: "San Francisco",
    lat: 37.7889,
    lng: -122.397,
    imageUrl: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=800&q=80",
    price: 15,
    capacity: 40,
    attendeeCount: 38,
    hostName: "Eng Interview Club",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=EIC",
    tags: ["interviews", "system-design", "career"],
    vibe: "intimate",
    soloFriendly: true,
    friendsGoing: [FRIENDS.jordan],
  },
  {
    id: "evt-9",
    title: "Post-Hackathon Afterparty 🎉",
    description:
      "Decompress after Ship It Weekend. DJ, retro arcade, demo showcase for teams that want feedback, and midnight ramen. Hackathon badge gets you in free.",
    category: "social",
    startAt: at(3, 21, 0),
    endAt: at(4, 2, 0),
    venue: "The Midway",
    address: "900 Marin St",
    city: "San Francisco",
    lat: 37.752,
    lng: -122.387,
    imageUrl: "https://images.unsplash.com/photo-1492684223066-81342eeff005?w=800&q=80",
    price: 0,
    capacity: 500,
    attendeeCount: 412,
    hostName: "BuildSF",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=BSF",
    tags: ["afterparty", "hackathon", "networking"],
    vibe: "crowds",
    soloFriendly: true,
    friendsGoing: [FRIENDS.priya, FRIENDS.kai, FRIENDS.sam, FRIENDS.alex],
  },
  {
    id: "evt-10",
    title: "DevRel & Developer Marketing Meetup",
    description:
      "Talk docs, DX, and community growth with DevRel leads from Vercel, Supabase, and Linear. Lightning talks + hallway track.",
    category: "professional",
    startAt: at(4, 18, 0),
    endAt: at(4, 21, 0),
    venue: "Linear HQ",
    address: "2261 Market St",
    city: "San Francisco",
    lat: 37.765,
    lng: -122.431,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    price: 0,
    capacity: 100,
    attendeeCount: 88,
    hostName: "DevRel Collective",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=DRC",
    tags: ["devrel", "developer-experience", "marketing"],
    vibe: "balanced",
    soloFriendly: true,
    friendsGoing: [FRIENDS.jordan],
  },
  {
    id: "evt-11",
    title: "Rust + WASM: Building Fast Web Apps",
    description:
      "Deep dive on Rust for performance-critical frontend and edge workloads. Two talks, one workshop slot, and office hours with wasm experts.",
    category: "learning",
    startAt: at(7, 18, 0),
    endAt: at(7, 21, 0),
    venue: "Mozilla Community Space",
    address: "2 Harrison St",
    city: "San Francisco",
    lat: 37.789,
    lng: -122.389,
    imageUrl: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800&q=80",
    price: 0,
    capacity: 50,
    attendeeCount: 47,
    hostName: "Rust Bay Area",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=RBA",
    tags: ["rust", "wasm", "performance"],
    vibe: "intimate",
    soloFriendly: true,
    friendsGoing: [FRIENDS.kai],
  },
  {
    id: "evt-12",
    title: "Berlin Hack Week — Green Tech Track",
    description:
      "European hackathon focused on climate + software. 72 hours, sustainability mentors, and seed grants for the top three teams.",
    category: "professional",
    startAt: at(5, 9, 0),
    endAt: at(8, 18, 0),
    venue: "Factory Berlin",
    address: "Rheinsberger Str. 76",
    city: "Berlin",
    lat: 52.532,
    lng: 13.3849,
    imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    price: 0,
    capacity: 250,
    attendeeCount: 231,
    hostName: "Hack Week Europe",
    hostAvatar: "https://api.dicebear.com/9.x/initials/svg?seed=HWE",
    tags: ["hackathon", "climate", "europe"],
    vibe: "crowds",
    soloFriendly: true,
    friendsGoing: [],
  },
];

export function getEventById(id: string, created: GatherEvent[] = []): GatherEvent | undefined {
  return [...created, ...MOCK_EVENTS].find((e) => e.id === id);
}

export function getAllEvents(created: GatherEvent[] = []): GatherEvent[] {
  return [...created, ...MOCK_EVENTS];
}
